stages:
  - build
  - test

before_script:

build:
  stage: build
  script:
    - docker pull qgis/qgis:release-3_4
    - docker pull qgis/qgis:release-3_10
    - docker pull qgis/qgis:release-3_12
    - docker run -d --name qgis-build -e DISPLAY=:99 qgis/qgis:release-3_10
    - sleep 2
    - docker exec qgis-build sh -c "pip3 install markdown2"
    - docker exec qgis-build sh -c "mkdir -p /coordinator"
    - docker cp . qgis-build:/coordinator
    - chmod +x scripts/build.sh
    - docker cp scripts/build.sh qgis-build:/
    - docker exec qgis-build sh -c "/build.sh /coordinator"
    - docker cp qgis-build:/coordinator coordinator
  artifacts:
    paths:
      - coordinator
    name: coordinator-${CI_COMMIT_REF_NAME}-pl${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}
    expire_in: 1 month
  after_script:
    - docker stop qgis-build
    - docker container rm qgis-build

run-tests-34:
  stage: test
  script:
    - docker run -d --name qgis-34 -e DISPLAY=:99 qgis/qgis:release-3_4
    - sleep 2
    - /bin/bash scripts/docker_test_setup.sh qgis-34
    - docker exec -t qgis-34 sh -c "qgis_testrunner.sh coordinator.test.run_all"
  after_script:
    - docker stop qgis-34
    - docker container rm qgis-34

run-tests-ltr:
  stage: test
  script:
    - docker run -d --name qgis-310 -e DISPLAY=:99 qgis/qgis:release-3_10
    - sleep 2
    - /bin/bash scripts/docker_test_setup.sh qgis-310
    - docker exec -t qgis-310 sh -c "qgis_testrunner.sh coordinator.test.run_all"
  after_script:
    - docker stop qgis-310
    - docker container rm qgis-310
    
run-tests-312:
  stage: test
  script:
    - docker run -d --name qgis-312 -e DISPLAY=:99 qgis/qgis:release-3_12
    - sleep 2
    - /bin/bash scripts/docker_test_setup.sh qgis-312
    - docker exec -t qgis-312 sh -c "qgis_testrunner.sh coordinator.test.run_all"
  after_script:
    - docker stop qgis-312
    - docker container rm qgis-312

